config/routes.rb
RubyGarage::Application.routes.draw do
  get "task_manager/index"
  
  delete "/:task_name", to: 'task_manager#delete_by_name', as: 'task_manager'
  get "/tasks/:id/edit_add", to: 'task_manager#priority_add', as: 'priority_add'
  get "/tasks/:id/edit_sub", to: 'task_manager#priority_sub', as: 'priority_sub'
  get "/tasks/:id/status", to: 'task_manager#status', as: 'status'
  
  resources :tasks

  root :to => 'task_manager#index', as: 'task_manager'

end

app/models/task.rb
class Task < ActiveRecord::Base
  after_initialize :default_values
  
  attr_accessible :dead_line, :priority, :status, :task, :task_name
  validates :priority, numericality: {greater_than_or_equal_to: 0}
  validates :task, :task_name, presence: true
  
  
  private
    def default_values
      self.status ||= "in action"
      self.priority ||= 0
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/task_manager_controller.rb
class TaskManagerController < ApplicationController
  def index
    @task_new = Task.new
    @tasks = Task.all.each do |obj|
    if obj.dead_line.acts_like?(:time)
      if obj.dead_line < (Time.now + (3*60*60))
          obj.status = "fail"
          obj.save
      end
    end  
    end
    @tasks = Task.order(:priority).all.group_by {|task| task.task_name}
  end
  
  def delete_by_name
  @task = Task.where task_name: (params[:task_name])
  @task.destroy_all

    respond_to do |format|
      format.html { redirect_to task_manager_url }
      format.json { head :no_content }
    end
  end

  def priority_add
    @task = Task.find(params[:id])
    @task.priority += 1
    @task.save
    
    respond_to do |format|
      format.html { redirect_to task_manager_url }
      format.json { head :no_content }
    end
  end

  def priority_sub
    @task = Task.find(params[:id])
    @task.priority -= 1
    @task.save
    
    respond_to do |format|
      format.html { redirect_to task_manager_url }
      format.json { head :no_content }
    end
  end

  def status
    @task = Task.find(params[:id])
    if @task.status == ("in action" or "fail")
      @task.status = "done"
    elsif @task.status
      @task.status = "in action"
    end
    @task.save
    
    respond_to do |format|
      format.html { redirect_to task_manager_url }
      format.json { head :no_content }
    end
  end
  

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_manager_url, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to task_manager_url, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to task_manager_url }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_manager_helper.rb
module TaskManagerHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>To Do List (by Edd)</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="span8 offset2">
            <h1 class="main_title">SIMPLE TO DO LIST</h1>
        </div>
    </div>
    <div class="row">
        <div class="span8 offset2">
            <%= yield %>
        </div>
    </div>
</div>

</body>
</html>

app/views/task_manager/_edit.html.erb
    <div class="well form-inline" method="post">
        <%= form_for(@task_new) do |f| %>
        <%= f.text_field :task_name, :value => @key %>
        <!-- <input type="text" class="span6" placeholder="Input task" name="inputing_task" /> -->
        <%= f.text_field :task %>
        <!-- <button type="submit" class="btn">Add</button> -->
        <%= f.submit %>
        <% end %>
    </div>

app/views/task_manager/index.html.erb
<div class="task_table">
<% @tasks.each_pair do |key, value| %>
    <div class="task_blok">
    <div class="row task_name">
    <div class="span6">
        <p><%= image_tag("glyphicons/png/glyphicons_039_notes.png") %>
           <%= key %></p>
    </div>
    <div class="offset2">
        <%= link_to image_tag("glyphicons/png/glyphicons_207_remove_2.png"),key, method: :delete,class: 'del_task_btn', data: { confirm: 'Are you sure?' } %>
    </div>
    </div>
    <div class="well form-inline" method="post">
        <%= form_for(@task_new) do |f| %>
        <%= f.text_field :task_name, :value => key, :class => "task_input_line" %>
        <%= f.text_field :task %>
        <%= f.submit :value => "Add Task", :class => "btn" %>
        <% end %>
    </div>
    <table class="table table-bordered">
        <% value.each do |obj| %>
                
                <% if obj.status == "done" %>
                <th class="text_content done">
                    <%= obj.task %>
                </th>
                <th class="options_content done">
                    <acronym title="Down Priority"><%= link_to image_tag("glyphicons/png/glyphicons_212_down_arrow.png"), priority_add_path(obj) %></acronym>
                    <acronym title="Up Priority"><%= link_to image_tag("glyphicons/png/glyphicons_213_up_arrow.png"), priority_sub_path(obj) %></acronym>
                    <acronym title="Edit"><%= link_to image_tag("glyphicons/png/glyphicons_150_edit.png"), edit_task_path(obj) %></acronym>
                    <acronym title="Delete Task"><%= link_to image_tag("glyphicons/png/glyphicons_207_remove_2.png"),obj, method: :delete, data: { confirm: 'Are you sure?' } %></acronym>
                    <acronym title="In Action"><%= link_to image_tag("glyphicons/png/glyphicons_151_new_window.png"), status_path(obj) %></acronym>
                </th>
        </tbody>
                <% elsif obj.status == "fail"%>
                <th class="text_content not_done">
                    <%= obj.task %>
                </th>
                <th class="options_content not_done">
                    <acronym title="Down Priority"><%= link_to image_tag("glyphicons/png/glyphicons_212_down_arrow.png"), priority_add_path(obj) %></acronym>
                    <acronym title="Up Priority"><%= link_to image_tag("glyphicons/png/glyphicons_213_up_arrow.png"), priority_sub_path(obj) %></acronym>
                    <acronym title="Edit"><%= link_to image_tag("glyphicons/png/glyphicons_150_edit.png"), edit_task_path(obj) %></acronym>
                    <acronym title="Delete Task"><%= link_to image_tag("glyphicons/png/glyphicons_207_remove_2.png"),obj, method: :delete, data: { confirm: 'Are you sure?' } %></acronym>
                </th>
        </tbody>
                <% else %>
                <th class="text_content">
                    <%= obj.task %>
                </th>
                <th class="options_content">
                    <acronym title="Down Priority"><%= link_to image_tag("glyphicons/png/glyphicons_212_down_arrow.png"), priority_add_path(obj) %></acronym>
                    <acronym title="Up Priority"><%= link_to image_tag("glyphicons/png/glyphicons_213_up_arrow.png"), priority_sub_path(obj) %></acronym>
                    <acronym title="Edit"><%= link_to image_tag("glyphicons/png/glyphicons_150_edit.png"), edit_task_path(obj) %></acronym>
                    <acronym title="Delete Task"><%= link_to image_tag("glyphicons/png/glyphicons_207_remove_2.png"),obj, method: :delete, data: { confirm: 'Are you sure?' } %></acronym>
                    <acronym title="Done"><%= link_to image_tag("glyphicons/png/glyphicons_152_check.png"), status_path(obj) %></acronym>                
                </th>
        </tbody>
                <% end %>

        <% end %>
    </table>
    </div>
<% end %>
<div align="center">
<%= link_to 'NEW TASK LIST', new_task_path, :class => 'btn btn-primary' %>
</div>
</div>

app/views/task_manager/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/_form.html.erb
<%= form_for @task, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :task_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :task_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :task, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :task, :class => 'text_area', rows: 6 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :status, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :dead_line, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :dead_line, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :priority, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :priority, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tasks_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= form_for @task, :html => { :class => 'form-horizontal' } do |f| %>

  <div class="control-group">
    <%= f.label :task, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :task, :class => 'text_area', rows: 6 %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :dead_line, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :dead_line, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :status, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                task_manager_url, :class => 'btn' %>
  </div>
<% end %>

app/views/tasks/index.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:task_name) %></th>
      <th><%= model_class.human_attribute_name(:task) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:dead_line) %></th>
      <th><%= model_class.human_attribute_name(:priority) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.id, task_path(task) %></td>
        <td><%= task.task_name %></td>
        <td><%= task.task %></td>
        <td><%= task.status %></td>
        <td><%= task.dead_line %></td>
        <td><%= task.priority %></td>
        <td><%=l task.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_task_path(task), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      task_path(task),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_task_path,
            :class => 'btn btn-primary' %>

app/views/tasks/new.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= form_for @task, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :task_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :task_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :task, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :task, :class => 'text_area', rows: 6 %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                task_manager_url, :class => 'btn' %>
  </div>
<% end %>

app/views/tasks/show.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:task_name) %>:</strong></dt>
  <dd><%= @task.task_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:task) %>:</strong></dt>
  <dd><%= @task.task %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @task.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dead_line) %>:</strong></dt>
  <dd><%= @task.dead_line %></dd>
  <dt><strong><%= model_class.human_attribute_name(:priority) %>:</strong></dt>
  <dd><%= @task.priority %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              tasks_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_task_path(@task), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              task_path(@task),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>